package HrSystem;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class EmployeeForm extends javax.swing.JFrame {

    Connection conn;
    Statement stm;

    public EmployeeForm() {
        initComponents();

        try {
            String url = "jdbc:mysql://localhost/hr management sis";
            String user = "root";
            String pass = "";

            conn = DriverManager.getConnection(url, user, pass);
            stm = conn.createStatement();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtepf = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtdesig = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtq = new javax.swing.JTextField();
        btnhome = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtdep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 518));
        getContentPane().setLayout(null);

        btnback.setBackground(new java.awt.Color(204, 204, 204));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(65, 403, 90, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add / Manage Employee Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 280, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("EPF_no                     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 120, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Employee Name     :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 120, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("       Age                          :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 140, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Designation             :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 100, 124, 32);

        txtepf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtepfActionPerformed(evt);
            }
        });
        getContentPane().add(txtepf);
        txtepf.setBounds(160, 110, 220, 30);

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(160, 160, 220, 30);

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        getContentPane().add(txtage);
        txtage.setBounds(160, 210, 220, 30);

        txtdesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesigActionPerformed(evt);
            }
        });
        getContentPane().add(txtdesig);
        txtdesig.setBounds(710, 100, 270, 30);

        btnsubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsubmit.setText("Save");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(730, 330, 72, 23);

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(820, 330, 72, 23);

        btnclear.setBackground(new java.awt.Color(204, 204, 204));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclear.setText("Clear All");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(400, 160, 80, 23);

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(910, 330, 70, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Salary                        :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 140, 120, 32);
        getContentPane().add(txtsalary);
        txtsalary.setBounds(710, 140, 270, 30);

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch);
        btnsearch.setBounds(400, 110, 80, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Contact                     :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 190, 120, 30);

        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontact);
        txtcontact.setBounds(710, 190, 270, 30);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("qulifications     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 240, 130, 30);
        getContentPane().add(txtq);
        txtq.setBounds(710, 240, 270, 70);

        btnhome.setBackground(new java.awt.Color(204, 204, 204));
        btnhome.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnhome.setText("Main menu");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome);
        btnhome.setBounds(180, 400, 110, 30);

        btnlogout.setBackground(new java.awt.Color(255, 102, 102));
        btnlogout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout);
        btnlogout.setBounds(890, 10, 100, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel9.setText("Department            :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 260, 120, 30);

        txtdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepActionPerformed(evt);
            }
        });
        getContentPane().add(txtdep);
        txtdep.setBounds(160, 260, 220, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HrSystem/cloud-based-hr-systems-innovating-hr-with-cutting-edge-technology.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1030, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtepfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtepfActionPerformed
    
    }//GEN-LAST:event_txtepfActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        try {
            String no = txtepf.getText();
            String Name = txtname.getText();
            int Age = Integer.parseInt(txtage.getText());
            String Designation = txtdesig.getText();
            String Department = txtdep.getText();

            int Salary = Integer.parseInt(txtsalary.getText());
            int Contact = Integer.parseInt(txtcontact.getText());
            String qualification = txtq.getText();

            String sql = "INSERT INTO tblemployee VALUES('" + no + "','" + Name + "','" + Age + "','" + Designation + "','" + Department + "'," + Salary + " ," + Contact + ",'" + qualification + "' )";
            int n = stm.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "employee Details Submitted");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, " Insert all details  ");
        } finally {
            clear();
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    public void clear() {
        txtepf.setText(null);
        txtname.setText(null);
        txtage.setText(null);
        txtdesig.setText(null);
        txtdep.setText(null);
        txtsalary.setText(null);
        txtcontact.setText(null);
        txtq.setText(null);
        txtepf.requestFocus();

    }

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            String no = txtepf.getText();
            String Name = txtname.getText();
            int Age = Integer.parseInt(txtage.getText());
            String Designation = txtdesig.getText();
            String Department = txtdep.getText();
            int Salary = Integer.parseInt(txtsalary.getText());
            int Contact = Integer.parseInt(txtcontact.getText());
            String qualification = txtq.getText();

            String sql = "UPDATE tblemployee SET Name='" + Name + "', Age=" + Age + ", Designation='" + Designation + "',Department='" + Department + "', Salary=" + Salary + ", Contact=" + Contact + ", qualification='" + qualification + "' WHERE EPF_no='" + no + "'";
            int n = stm.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "employee Details UPDATED");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        } finally {
            clear();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            String no = txtepf.getText();

            String sql = "DELETE FROM tblemployee WHERE EPF_no='" + no + "'";

            int n = stm.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "employee Details DELETED");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        } finally {
            clear();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            String no = txtepf.getText();

            String sql = "SELECT * FROM tblemployee WHERE EPF_no='" + no + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.isBeforeFirst()) {
                rs.next();
                txtname.setText(rs.getString(2));
                txtage.setText(rs.getString(3));
                txtdesig.setText(rs.getString(4));
                txtdep.setText(rs.getString(5));
                txtsalary.setText(rs.getString(6));
                txtcontact.setText(rs.getString(7));
                txtq.setText(rs.getString(8));

            } else {
                JOptionPane.showMessageDialog(this, "employee Details not Found");
                clear();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        Home fp = new Home();
        fp.show();
        dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        login lg = new login();
        lg.show();
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        Interfacehrmanager ifm = new Interfacehrmanager();
        ifm.show();
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtdesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdep;
    private javax.swing.JTextField txtdesig;
    private javax.swing.JTextField txtepf;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtq;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
